
# source = ~/.config/hypr/config/defaults.conf

# exec-once = systemctl --user start hyprpolkitagent
# exec-once = /usr/lib/xdg-desktop-portal
# exec-once = /usr/lib/xdg-desktop-portal-hyprland

# # ## Slow app launch fix
# exec-once = systemctl --user import-environment &
# exec-once = hash dbus-update-activation-environment 2>/dev/null &
# exec-once = dbus-update-activation-environment --systemd &

# ## Idle configuration
# exec-once = $idlehandler
# exec-once = ambxst

exec-once = hyprpm enable hyprEasymotion
exec-once = glance --config ~/.config/glance/config.yaml
exec-once = systemctl --user start hyprpolkitagent
exec = pgrep -x "hypridle" > /dev/null || hypridle
